spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sfumtim/ConfigData
          username: Sfumtim
          password: Simson@01
server:
  port: 8002
health:
  config:
    enabled: false           